name: Trigger auto deployment for pantryapp-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PANTRYAPPFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PANTRYAPPFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PANTRYAPPFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Docker Login to ACR
        run: |
          echo "${{ secrets.PANTRYAPPFRONTEND_REGISTRY_PASSWORD }}" | docker login ${{ secrets.PANTRYAPPFRONTEND_REGISTRY_URL }} \
            -u "${{ secrets.PANTRYAPPFRONTEND_REGISTRY_USERNAME }}" \
            --password-stdin

      - name: Build and Push Frontend Image
        run: |
          docker build \
            -f pantry_app_client/Dockerfile \
            -t ${{ secrets.PANTRYAPPFRONTEND_REGISTRY_URL }}/pantryapp-frontend:${{ github.sha }} \
            ./pantry_app_client

          docker push ${{ secrets.PANTRYAPPFRONTEND_REGISTRY_URL }}/pantryapp-frontend:${{ github.sha }}

      - name: Deploy Frontend to Azure Container App
        run: |
          az containerapp update \
            --name ${{ secrets.PANTRYAPPFRONTEND_APP_NAME }} \
            --resource-group ${{ secrets.PANTRYAPPFRONTEND_RESOURCE_GROUP }} \
            --image ${{ secrets.PANTRYAPPFRONTEND_REGISTRY_URL }}/pantryapp-frontend:${{ github.sha }}
