name: Trigger auto deployment for pantryapp-backend

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - ".github/workflows/pantryapp-backend-AutoDeployTrigger-60fae0a7-131f-4370-a7e0-b610f8c8749c.yml"

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PANTRYAPPBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PANTRYAPPBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PANTRYAPPBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/pantry_app_server

          dockerfilePath: pantry_app_server/Dockerfile

          registryUrl: pantryapp-ftezc4heducvhcey.azurecr.io
          registryUsername: ${{ secrets.PANTRYAPPBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PANTRYAPPBACKEND_REGISTRY_PASSWORD }}

          containerAppName: pantryapp-backend
          resourceGroup: myresourcegroup

          imageToBuild: pantryapp-ftezc4heducvhcey.azurecr.io/pantryapp-backend:${{ github.sha }}
